config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :actors
  root to: 'top#index'
end

app/models/actor.rb
# frozen_string_literal: true

class Actor < ApplicationRecord
  has_many :event
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :actor
  self.inheritance_column = :_type_disabled
end

app/models/github/actor.rb
# frozen_string_literal: true

class Github::Actor < Github::Client
  def self.get(date: nil)
    new.get(date)
  end

  def get(date)
    if date
      response = @client.search_issues "repo:oss-gate/workshop is:issue created: #{date.to_s}"
    else
      response = @client.search_issues 'repo:oss-gate/workshop is:issue'
    end

    response.items.each do |res|
      ::Actor.create(name: res[:user][:login], icon_url: res[:user][:avatar_url])
    rescue ActiveRecord::RecordNotUnique => e
      puts e
    end
  end
end

app/models/github/client.rb
# frozen_string_literal: true

class Github::Client
  def initialize
    @client = Octokit::Client.new access_token: ENV['GITHUB_ACCESS_TOKEN']
    @client.auto_paginate = true
  end
end

app/models/github/event.rb
# frozen_string_literal: true

class Github::Event < Github::Client
  EVENT_LIST = %w[PushEvent CreateEvent IssueEvent PullRequestEvent PullRequestReviewCommentEvent].freeze

  def self.get(limit: 50, offset: 0)
    new.get(limit, offset)
  end

  def get(limit, offset)
    actors = ::Actor.all.limit(limit).offset(offset)

    actors.each do |actor|
      response = @client.user_public_events actor.name
      response.select { |res| EVENT_LIST.include? res[:type] }.map do |res|
        target_url = target_url(res)

        next if target_url.blank?

        ::Event.create(actor_id: actor.id, type: res[:type].downcase, timestamp: res[:created_at], target_url: target_url)
      end
    end
  end

  private

  def target_url(res)
    case res[:type]
    when 'PushEvent'
      "https://github.com/#{res[:repo][:name]}/commit/#{res[:payload][:commits]&.first&.[](:sha)}"
    when 'PullRequestEvent'
      res[:payload][:pull_request][:html_url]
    when 'CreateEvent'
      "https://github.com/#{res[:repo][:name]}"
    when 'IssueEvent'
      res[:payload][:issue][:html_url]
    when 'PullRequestReviewCommentEvent'
      res[:payload][:comment][:html_url]
    end
  end
end

app/controllers/actors_controller.rb
# frozen_string_literal: true

class ActorsController < ApplicationController
  before_action :set_actor, only: :show

  def index
    @actors = Actor.all
  end

  def show; end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def index
    @events = Event.includes(:actor).order(timestamp: :DESC)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.icon_url %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Icon url:</strong>
  <%= @actor.icon_url %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Illuminate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.slim
.page
  .page__demo
    .main-container.page__container
      .timeline
        .timeline__group
          - year = nil
          - @events.each do |event|
            - if year != event.timestamp.year
              span.timeline__year
                = year = event.timestamp.year
            .timeline__box
              .timeline__date
                span.timeline__month
                  = day = event.timestamp.month
                span.timeline__day
                  = day = event.timestamp.day
              .timeline__post
                .timeline__content
                  img height="50px" src=event.actor.icon_url
                  a href="https://github.com/#{event.actor.name}"
                    = event.actor.name
                  a href="#{event.target_url}"
                    = " " + event.type